import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import profile from '@/public/images/profile.jpg'
import instagram from '@/public/images/instagram.png'
import discord from '@/public/images/discord.png'
import twitter from '@/public/images/twitter.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gradient-to-r from-green-900 to-blue-400 h-screen flex flex-col justify-center items-center text-white'>
        <Image src={profile} className='w-24 rounded-full m-4 shadow-xl'/>
        <h1 className='font-bold text-lg'>@chad_ki_gibson</h1>
        <h2 className='text-[18px] m-1'></h2>
        
        <div className='m-5 w-[300px]'>
          <button className='w-[300px]' onClick={() => {event.preventDefault();window.open("https://instagram.com/chad_ki_gibson/", "_blank");}}>
            <div className= 'bg-[#212121] rounded-full p-3 my-3 flex justify-center items-center transition-all hover:scale-110 hover:border-[1px] hover:bg-transparent'>
            <Image src={instagram}className='w-4 mx-1 h-4'/>
              <p>Instagram</p>
            </div>
          </button>
          <button className='w-[300px]' onClick={() => {event.preventDefault();window.open("https://instagram.com/chad_ki_gibson/", "_blank");}}>
            <div className= 'bg-[#212121] rounded-full p-3 my-3 flex justify-center items-center transition-all hover:scale-110 hover:border-[1px] hover:bg-transparent'>
            <Image src={twitter}className='w-4 mx-1 '/>
              <p>Twitter</p>
            </div>
          </button>
          <button className='w-[300px]' onClick={() => {event.preventDefault();window.open("https://instagram.com/chad_ki_gibson/", "_blank");}}>
            <div className= 'bg-[#212121] rounded-full p-3 my-3 flex justify-center items-center transition-all hover:scale-110 hover:border-[1px] hover:bg-transparent'>
            <Image src={discord}className='w-4 mx-1 '/>
              <p>Discord</p>
            </div>
          </button>
        </div>
      </div>
    </>
);
}
